from app.models import db, Day

def seed_days():

    # block 1
    day1 = Day(notes="", week_id=1)
    day2 = Day(notes="", week_id=1)
    day3 = Day(notes="", week_id=1)
    day4 = Day(notes="", week_id=1)
    day5 = Day(notes="", week_id=2)
    day6 = Day(notes="", week_id=2)
    day7 = Day(notes="", week_id=2)
    day8 = Day(notes="", week_id=2)
    day9 = Day(notes="", week_id=3)
    day10 = Day(notes="", week_id=3)
    day11 = Day(notes="", week_id=3)
    day12 = Day(notes="", week_id=3)
    day13 = Day(notes="", week_id=4)
    day14 = Day(notes="", week_id=4)
    day15 = Day(notes="", week_id=4)
    day16 = Day(notes="", week_id=4)
    day17 = Day(notes="", week_id=5)
    day18 = Day(notes="", week_id=5)
    day19 = Day(notes="", week_id=5)
    day20 = Day(notes="", week_id=5)
    day21 = Day(notes="", week_id=6)
    day22 = Day(notes="", week_id=6)
    day23 = Day(notes="", week_id=6)
    day24 = Day(notes="", week_id=6)

    # block 2
    day25 = Day(notes="", week_id=7)
    day26 = Day(notes="", week_id=7)
    day27 = Day(notes="", week_id=7)
    day28 = Day(notes="", week_id=7)
    day29 = Day(notes="", week_id=7)
    day30 = Day(notes="", week_id=7)
    day31 = Day(notes="", week_id=8)
    day32 = Day(notes="", week_id=8)
    day33 = Day(notes="", week_id=8)
    day34 = Day(notes="", week_id=8)
    day35 = Day(notes="", week_id=8)
    day36 = Day(notes="", week_id=8)
    day37 = Day(notes="", week_id=9)
    day38 = Day(notes="", week_id=9)
    day39 = Day(notes="", week_id=9)
    day40 = Day(notes="", week_id=9)
    day41 = Day(notes="", week_id=9)
    day42 = Day(notes="", week_id=9)
    day43 = Day(notes="", week_id=10)
    day44 = Day(notes="", week_id=10)
    day45 = Day(notes="", week_id=10)
    day46 = Day(notes="", week_id=10)
    day47 = Day(notes="", week_id=10)
    day48 = Day(notes="", week_id=10)


    db.session.add(day1)
    db.session.add(day2)
    db.session.add(day3)
    db.session.add(day4)
    db.session.add(day5)
    db.session.add(day6)
    db.session.add(day7)
    db.session.add(day8)
    db.session.add(day9)
    db.session.add(day10)
    db.session.add(day11)
    db.session.add(day12)
    db.session.add(day13)
    db.session.add(day14)
    db.session.add(day15)
    db.session.add(day16)
    db.session.add(day17)
    db.session.add(day18)
    db.session.add(day19)
    db.session.add(day20)
    db.session.add(day21)
    db.session.add(day22)
    db.session.add(day23)
    db.session.add(day24)
    db.session.add(day25)
    db.session.add(day26)
    db.session.add(day27)
    db.session.add(day28)
    db.session.add(day29)
    db.session.add(day30)
    db.session.add(day31)
    db.session.add(day32)
    db.session.add(day33)
    db.session.add(day34)
    db.session.add(day35)
    db.session.add(day36)
    db.session.add(day37)
    db.session.add(day38)
    db.session.add(day39)
    db.session.add(day40)
    db.session.add(day41)
    db.session.add(day42)
    db.session.add(day43)
    db.session.add(day44)
    db.session.add(day45)
    db.session.add(day46)
    db.session.add(day47)
    db.session.add(day48)


    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_days():
    db.session.execute('TRUNCATE days RESTART IDENTITY CASCADE;')
    db.session.commit()
