"""changed exercise name constraint to 60 chars

Revision ID: 94a18d308fd8
Revises: 7af09ab2aacd
Create Date: 2022-06-11 16:03:02.733677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a18d308fd8'
down_revision = '7af09ab2aacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'total_vol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('total_vol', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
