"""took out start_date

Revision ID: 67c2049716ee
Revises: 36ed7c626e58
Create Date: 2022-06-07 11:19:43.198994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c2049716ee'
down_revision = '36ed7c626e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weeks', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weeks', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
