"""added friend_id to room model

Revision ID: 675bc64bb7ac
Revises: 94a18d308fd8
Create Date: 2022-06-13 13:56:58.650506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675bc64bb7ac'
down_revision = '94a18d308fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('friend_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'users', ['friend_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'friend_id')
    # ### end Alembic commands ###
