"""exercise nullable

Revision ID: 9ff249bd63a5
Revises: 67c2049716ee
Create Date: 2022-06-08 14:43:57.749980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff249bd63a5'
down_revision = '67c2049716ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('exercises', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'reps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'rpe',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'rpe',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'reps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
